export const FETCH_GROUP_ORDER_ARTICLES = 'FETCH_GROUP_ORDER_ARTICLES';
export const FETCH_GROUP_ORDER_ARTICLES_REQUEST = `${FETCH_GROUP_ORDER_ARTICLES}_REQUEST`;
export const FETCH_GROUP_ORDER_ARTICLES_SUCCESS = `${FETCH_GROUP_ORDER_ARTICLES}_SUCCESS`;
export const FETCH_GROUP_ORDER_ARTICLES_FAILURE = `${FETCH_GROUP_ORDER_ARTICLES}_FAILURE`;

export const UPDATE_GROUP_ORDER_ARTICLE = 'UPDATE_GROUP_ORDER_ARTICLE';
export const UPDATE_GROUP_ORDER_ARTICLE_OPTIMIST = `${UPDATE_GROUP_ORDER_ARTICLE}_OPTIMIST`;
export const UPDATE_GROUP_ORDER_ARTICLE_REQUEST = `${UPDATE_GROUP_ORDER_ARTICLE}_REQUEST`;
export const UPDATE_GROUP_ORDER_ARTICLE_SUCCESS = `${UPDATE_GROUP_ORDER_ARTICLE}_SUCCESS`;
export const UPDATE_GROUP_ORDER_ARTICLE_FAILURE = `${UPDATE_GROUP_ORDER_ARTICLE}_FAILURE`;

export const CREATE_GROUP_ORDER_ARTICLE = 'CREATE_GROUP_ORDER_ARTICLE';
export const CREATE_GROUP_ORDER_ARTICLE_OPTIMIST = `${CREATE_GROUP_ORDER_ARTICLE}_OPTIMIST`;
export const CREATE_GROUP_ORDER_ARTICLE_REQUEST = `${CREATE_GROUP_ORDER_ARTICLE}_REQUEST`;
export const CREATE_GROUP_ORDER_ARTICLE_SUCCESS = `${CREATE_GROUP_ORDER_ARTICLE}_SUCCESS`;
export const CREATE_GROUP_ORDER_ARTICLE_FAILURE = `${CREATE_GROUP_ORDER_ARTICLE}_FAILURE`;

export function fetchGroupOrderArticles(query) {
  return { type: FETCH_GROUP_ORDER_ARTICLES, payload: { q: query } };
}

export function updateGroupOrderArticle(id, payload) {
  return { type: UPDATE_GROUP_ORDER_ARTICLE, id, payload };
}

export function createGroupOrderArticle(payload) {
  return { type: CREATE_GROUP_ORDER_ARTICLE, payload };
}
