export const FETCH_ORDER_ARTICLES = 'FETCH_ORDER_ARTICLES';
export const FETCH_ORDER_ARTICLES_REQUEST = `${FETCH_ORDER_ARTICLES}_REQUEST`;
export const FETCH_ORDER_ARTICLES_SUCCESS = `${FETCH_ORDER_ARTICLES}_SUCCESS`;
export const FETCH_ORDER_ARTICLES_FAILURE = `${FETCH_ORDER_ARTICLES}_FAILURE`;

export function fetchOrderArticles() {
  return { type: FETCH_ORDER_ARTICLES };
}
