export const FETCH_ORDER_ARTICLES = 'FETCH_ORDER_ARTICLES';
export const FETCH_ORDER_ARTICLES_REQUEST = `${FETCH_ORDER_ARTICLES}_REQUEST`;
export const FETCH_ORDER_ARTICLES_SUCCESS = `${FETCH_ORDER_ARTICLES}_SUCCESS`;
export const FETCH_ORDER_ARTICLES_FAILURE = `${FETCH_ORDER_ARTICLES}_FAILURE`;

export const FETCH_ORDER_ARTICLE = 'FETCH_ORDER_ARTICLE';
export const FETCH_ORDER_ARTICLE_REQUEST = `${FETCH_ORDER_ARTICLE}_REQUEST`;
export const FETCH_ORDER_ARTICLE_SUCCESS = `${FETCH_ORDER_ARTICLE}_SUCCESS`;
export const FETCH_ORDER_ARTICLE_FAILURE = `${FETCH_ORDER_ARTICLE}_FAILURE`;

// used by group_order_article saga
export const INTERNAL_UPDATE_ORDER_ARTICLE_OPTIMIST = `INTERNAL_UPDATE_ORDER_ARTICLE_OPTIMIST`;

export function fetchOrderArticles() {
  return { type: FETCH_ORDER_ARTICLES };
}
